"""
Metric model for analysis results.

Represents computed metrics and insights generated by the Analysis module
from collected raw data. These are derived data fields for dashboard consumption.
"""

from sqlalchemy import String, Float, Text, ForeignKey, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from momento_core.db.base import BaseModel, TimestampMixin
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from momento_core.db.models.collected_data import CollectedData


class Metric(BaseModel, TimestampMixin):
    """
    Computed metric from analysis of collected data.
    
    This table stores analysis results including statistical aggregations,
    trend indicators, anomaly detection results, and other derived metrics.
    
    Attributes:
        id: Unique identifier
        collected_data_id: Foreign key to source collected data
        metric_type: Type of metric (e.g., 'aggregation', 'trend', 'anomaly')
        metric_name: Name of the specific metric (e.g., 'moving_average', 'std_dev')
        value: Computed metric value
        unit: Unit of measurement (e.g., 'percent', 'multiplier')
        metadata: JSON string with additional metric metadata
        collected_data: Relationship to CollectedData
    """
    
    __tablename__ = "metrics"
    
    collected_data_id: Mapped[int] = mapped_column(
        ForeignKey("collected_data.id"),
        nullable=False,
        index=True,
        doc="Foreign key to the source collected data"
    )
    
    metric_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        doc="Type of metric (aggregation, trend, anomaly, etc.)"
    )
    
    metric_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        doc="Name of the specific metric"
    )
    
    value: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc="Computed metric value"
    )
    
    unit: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        doc="Unit of measurement"
    )
    
    meta_data: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="JSON string with additional metric metadata"
    )
    
    # Relationships
    collected_data: Mapped["CollectedData"] = relationship(
        back_populates="metrics",
        foreign_keys="Metric.collected_data_id"
    )
    
    # Indexes for common query patterns
    __table_args__ = (
        Index("idx_metrics_type_name", "metric_type", "metric_name"),
        Index("idx_metrics_collected_data_type", "collected_data_id", "metric_type"),
    )
    
    def __repr__(self) -> str:
        """String representation of Metric."""
        return f"<Metric(id={self.id}, type={self.metric_type}, name={self.metric_name}, value={self.value})>"
