// Regenerates src/docs/generated.ts from src/docs/*.md (runs on every build).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const dir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "docs");
const files = readdirSync(dir).filter((f) => f.endsWith(".md")).sort();
let out = "// AUTO-GENERATED from src/docs/*.md — do not edit by hand.\n// Regenerated by scripts/generate-docs.mjs on every build.\nexport const DOCS_RAW: Record<string, string> = {\n";
for (const f of files) out += `  ${JSON.stringify(f.replace(/\.md$/, ""))}: ${JSON.stringify(readFileSync(join(dir, f), "utf8"))},\n`;
out += "};\n";
writeFileSync(join(dir, "generated.ts"), out);
console.log(`docs: ${files.length} pages → src/docs/generated.ts`);
